#!/usr/bin/env bash

function _unzip-strip() {
    # shopt is a bash built-in command. Zsh, has setopt instead
    # so, set the command according to the type of shell (only supports bash and zsh)
    local SHOPT="shopt"

    if [[ "$SHELL" == *zsh ]]; then
        SHOPT="setopt"
    fi

    local zip="$1"
    local dest="${2:-.}"
    local temp=$(mktemp -d)

    unzip -d "$temp" "$zip"
    mkdir -p "$dest"
    $SHOPT -s dotglob
    local f=("$temp"/*)

    if (( ${#f[@]} == 1 )) && [[ -d "${f[0]}" ]] ; then
        mv "$temp"/*/* "$dest"
    else
        mv "$temp"/* "$dest"
    fi
    rm -rf "$temp"

}