#!/usr/bin/env bash

evm_help() {
    evm_echo "

Usage: evm [command]

    Description:
    EVM is the Erlang Version Manager.

    Commands:
    version       - print the evm version number
    help          - display this usage text
    list_remote   - list available versions
    install       - install erlang version
    uninstall     - uninstall erlang version
    remove        - remove the whole stuff related to this version
    list          - list installed erlang versions
    default       - set an erlang version as system default
    use           - select an erlang version to use
    download      - download erlang tar file
    system        - leaving only the system version of ERLANG available
    implode       - completely remove evm
"
}
