#!/usr/bin/env bash


__update_scripts_evm_for_erlang_default() {
    if [[ ! -f "$1" ]]; then
        evm_warn "Does not exist $EVM_HOME/scripts/evm file on your system"
        return 1
    fi

    local source_line="[[ -s $EVM_HOME/evm_config/erlang_default ]] && version=\$(cat $EVM_HOME/evm_config/erlang_default) && evm use \$version > /dev/null"
    grep -F "$source_line" "$1" > /dev/null 2>&1
    if [ $? -ne 0 ]; then
        echo -e "# evm use erlang_default for new terminal session.\n$source_line" >> "$1"
    fi
}

# set this erlang version as system default.
# @params: erlang_version, e.g. 22.3.2
evm_default() {
    local VERSION=$1

    if [[ -d $ERLANG_VERSIONS_LOCATION/$VERSION ]]; then

        if [[ ! -d $EVM_HOME/evm_config ]] ; then
            evm_dev_info "
            Counld not find $EVM_HOME/evm_config directory in your system.
            evm will create this file automatically.
            "
            mkdir -p $EVM_HOME/evm_config
        fi

        if [[ ! -f $EVM_HOME/evm_config/erlang_default ]] ; then
            evm_dev_info "
            Counld not find $EVM_HOME/evm_config/erlang_default file in your system.
            evm will create this file automatically.
            "
            touch $EVM_HOME/evm_config/erlang_default
        fi

        __update_scripts_evm_for_erlang_default "$EVM_HOME/scripts/evm"

        echo "$VERSION" > $EVM_HOME/evm_config/erlang_default
        evm_dev_info "=== evm_use $VERSION ==="
        evm_use $VERSION
    else
        evm_error "
        $VERSION is not installed yet.

        Use 'evm install $VERSION' to install it
        "
        return 1
    fi
}
