#!/usr/bin/env bash

# remove the erlang version from the evm space
evm_remove() {
    local VERSION=$1
    local ERLANG_VERSION_ZIP_FILE=$FILE_PREFIX-$VERSION.$FILE_EXTENSION

    evm_uninstall $VERSION

    if [[ -f $ERLANG_TARS_LOCATION/$ERLANG_VERSION_ZIP_FILE ]]; then
        evm_message "Removing $VERSION..."
        rm -rf $ERLANG_TARS_LOCATION/$ERLANG_VERSION_ZIP_FILE
        evm_message "Removed successfully"
    else
        evm_message "$VERSION not downloaded"
        return 0
    fi
}
