#!/usr/bin/env bash

__update_scripts_evm_for_evm_use() {
	local EVM_FILE="$1"
	local VERSION="$2"

	if [[ ! -f "$EVM_FILE" ]]; then
        evm_warn "Does not exist $EVM_FILE file on your system"
        return 1
    fi

	for directory in $ERLANG_VERSIONS_LOCATION/*; do
        evm_dev_info "--------------------------"
        evm_dev_info "directory => $directory"
        evm_dev_info "--------------------------"
        PATH="$(echo $PATH | sed -e "s,$directory/bin,,g ; s,^:,, ; s,::,:,g ; s,:$,,")"
	done

	local source_line="export PATH=$PATH:$ERLANG_VERSIONS_LOCATION/$VERSION/bin"

	echo "grep -F \"export PATH=\" $EVM_FILE > /dev/null 2>&1"
	grep -F "export PATH=" $EVM_FILE > /dev/null 2>&1

	if [[ $? -eq 0 ]]; then
		sed -i '/export PATH=.*\/erlang_versions\/.*\/bin/d' $EVM_FILE
	fi

	echo -e "\n$source_line" >> $EVM_FILE
}


# set this erlang version to be the one available in the PATH
# @params: erlang_version, e.g. 22.3.2
evm_use() {
    local VERSION=$1

    if [[ -d $ERLANG_VERSIONS_LOCATION/$VERSION ]]; then
        __update_scripts_evm_for_evm_use "$EVM_HOME/scripts/evm" "$VERSION"

        evm_success_echo ""
        evm_success_echo ""
        evm_success_echo "Please restart your terminal session, or to get started execute the following command to make it effective."
        evm_success_echo ""
        evm_success_echo "       source $EVM_HOME/scripts/evm      "
        evm_success_echo ""
	else
        evm_warn "

Erlang Version $VERSION has not been installed in $ERLANG_VERSIONS_LOCATION/$VERSION.
Use 'evm install $VERSION' to install it.
        "
        return 1
    fi
}
